Header layout
strapi/design-system-experiments pull request #163
Opened 2021-07-06 07:33 UTC by mfrachet

# [title]

## Description
[add description]

## Demo
Example on : [deployed story link]

## API
[api details]

```jsx
 <HeaderLayout
  sticky
  navigationAction={
    <Link startIcon={<BackIcon />} to="/">
      <VisuallyHidden>Go back</VisuallyHidden>
    </Link>
  }
  primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
  secondaryAction={
    <Button variant="tertiary" startIcon={<EditIcon />}>
      Edit
    </Button>
  }
  title={<H2>Restaurants</H2>}
  subtitle={
    <Text small={true} textColor="neutral600">
      36 entries found
    </Text>
  }
/>
```

## Voiceover

<img width="714" alt="Screenshot 2021-07-06 at 09 32 39" src="https://user-images.githubusercontent.com/3874873/124560501-292b3180-de3d-11eb-8da0-c4425733ea4e.png">
<img width="694" alt="Screenshot 2021-07-06 at 09 32 48" src="https://user-images.githubusercontent.com/3874873/124560502-29c3c800-de3d-11eb-86a4-6e5942fbd824.png">

2021-07-06 10:09 UTC, HichamELBSI approved these changes
LGTM good job !!

2021-07-06 12:42 UTC, maevalienard commented
Ciao bambino,

First of all, great job :D 

- Not sure if your buttons have a SmallButton text style. I feel like it uses more like a SmallText style actually. That would explain the "strange" balance between the icon size and the text :) 
- Why did you put the Edit button on the right side of the sticky header? :) 
- On the fixed header, the text button should say "back" and not "go back" but I'm okay with both wording. We just need to make a decision and I'd edit the design accordingly :) 
- Is it the right text style font for the description of the fixed header? I find it slightly too bold but it's probably just my eyes. 
- Would it be possible to remove the 4px spacing between the H1 and the description in the fixed header, please? I feel like the balance is better without :) 
- I feel like there's a slight misalignment for that component. The arrow seems upper to me than the label. 
<img width="238" alt="Capture d’écran 2021-07-06 à 14 41 40" src="https://user-images.githubusercontent.com/54801383/124601602-53deaf80-de68-11eb-8ea4-68b55518f925.png">

Many thanks in advance 🙏

2021-07-06 12:43 UTC, maevalienard requested changes
See my previous comment (still not very familiar with GitHub uh sorry for that)

2021-07-06 13:01 UTC, mfrachet commented
> Not sure if your buttons have a SmallButton text style. I feel like it uses more like a SmallText style actually. That would explain the "strange" balance between the icon size and the text :)

The buttons are the exact ones defined in https://design-system-alpha.vercel.app/?path=/story/design-system-atoms-button--variants

> Why did you put the Edit button on the right side of the sticky header? :)

It's just a button, we can change the label on the fly, it's not an "edit" button, but a button with a "edit" label

> On the fixed header, the text button should say "back" and not "go back" but I'm okay with both wording. We just need to make a decision and I'd edit the design accordingly :)

Same as above, this is not fixed content. We can change it from Strapi core side

> Is it the right text style font for the description of the fixed header? I find it slightly too bold but it's probably just my eyes.

I'm using Text body small from https://design-system-alpha.vercel.app/?path=/story/design-system-molecules-text--base

> Would it be possible to remove the 4px spacing between the H1 and the description in the fixed header, please? I feel like the balance is better without :)

Yes sure 😊 Can we also remove it from the documentation in Figma to stay consistent 🙏🏻 ?

> I feel like there's a slight misalignment for that component. The arrow seems upper to me than the label.

This is the link component in https://design-system-alpha.vercel.app/?path=/story/design-system-atoms-link--base . Changing it will make it change everywhere

2021-07-06 13:15 UTC, maevalienard commented
> The buttons are the exact ones defined in https://design-system-alpha.vercel.app/?path=/story/design-system-atoms-button--variants

Might not be the right text-style in the buttons then :/ I struggle to verify :( 

> It's just a button, we can change the label on the fly, it's not an "edit" button, but a button with a "edit" label

I understood, the thing is would that be a possibility to have the Edit button right next to the maintitle & description then? Whether it's an "Edit" or not since you mentioned the label doesn't really matter, and whether it's optional. It's just because it's the CTB the Edit button remains next to that part :) 

> Same as above, this is not fixed content. We can change it from Strapi core side

Which one do you like best then? :) 

> I'm using Text body small from https://design-system-alpha.vercel.app/?path=/story/design-system-molecules-text--base

I think you mean you used that on the sticky header, I meant on the default one. Sorry I wasn't clear :) 
 

> Yes sure 😊 Can we also remove it from the documentation in Figma to stay consistent 🙏🏻 ?

Absolutely 🌻 


> This is the link component in https://design-system-alpha.vercel.app/?path=/story/design-system-atoms-link--base . Changing it will make it change everywhere

No problemo, the misalignment is global :)

2021-07-06 14:21 UTC, soupette approved these changes
LGTM

2021-07-06 14:21 UTC, soupette commented on packages/strapi-design-system/src/HeaderLayout/HeaderLayout.js
> +            {primaryAction ? <Box paddingLeft={2}>{primaryAction}</Box> : undefined}
You can do `primaryAction && <Box>...</Box>`

2021-07-06 14:21 UTC, soupette commented on packages/strapi-design-system/src/HeaderLayout/HeaderLayout.js
> +      {navigationAction ? <Box paddingBottom={3}>{navigationAction}</Box> : null}
Same here you can remove the ternary

2021-07-06 14:21 UTC, soupette commented on packages/strapi-design-system/src/HeaderLayout/HeaderLayout.js
> +  sticky: undefined,
Why not setting it to false?

2021-07-07 08:58 UTC, merged

2021-07-07 10:50 UTC, maevalienard commented
Did you push the changes on vercel yet?

2021-07-07 13:04 UTC, mfrachet commented
> Did you push the changes on vercel yet?

Yes they are

2021-07-07 13:11 UTC, maevalienard commented
Even for the boldness of the buttons? 🤔

2021-07-07 13:14 UTC, mfrachet commented
I do think so, it uses the same as the one from this story: https://design-system-git-fix-link-button-strapijs.vercel.app/?path=/story/design-system-atoms-button--variants . Something looks not okay?

2021-07-07 14:13 UTC, maevalienard commented
I hard refresh and still see a font-weight: 400 for the button labels. Also it seems like the Text button component still have the old alignment (not sure about that one but pretty sure about the buttons) :)

2021-07-08 07:26 UTC, mfrachet commented
@maevalienard is it still the same on https://design-system-alpha.vercel.app/?path=/story/design-system-layouts-headerlayouts--base ? Maybe I didn't rebase before merging and so, you see an older version 😓

2021-07-08 08:09 UTC, maevalienard commented
Looks goooood 🚀 Thank you!